export enum GlobalUiEvent{
    MAIN_MENUE_VISIBILITY,
    MODAL_CLOSE,
    POPOVER_CLOSE,
    FILE_UPLOAD,
    LOADER_CLOSE,
    LOADER_OPEN,
    CONFRIM_DIALOG,
    CONFRIM_DIALOG_CLOSE,
    REMOVE_JOURNAL
}